inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/**/*'
    - 'vendor/**/*'

Metrics:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/Lambda:
  Enabled: false

# enable both hash-rocket and ruby19 hashmap syntax
Style/HashSyntax:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

#Allow both ['a', 'b'], %w[a b] and %w(a b) style arrays
Style/WordArray:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/InverseMethods:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/Loop:
  Enabled: false
